name: check against helix tree-sitter queries

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install yarn -g
        npm install tree-sitter-cli -g
    - name: Generate tree-sitter parser
      run: tree-sitter generate
    - name: pull queries from helix
      working-directory: ./queries
      run: |
       wget "https://raw.githubusercontent.com/beeb/helix/refs/heads/master/runtime/queries/solidity/highlights.scm"
       wget "https://raw.githubusercontent.com/beeb/helix/refs/heads/master/runtime/queries/solidity/locals.scm"
       wget "https://raw.githubusercontent.com/beeb/helix/refs/heads/master/runtime/queries/solidity/textobjects.scm"
    - run: yarn
    - run: yarn test
